spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    maximum-pool-size: 5
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch.matching-strategy: ant_path_matcher
r2dbc:
  migrate:
    resources-paths:
      - classpath:/db/migration/*.sql