CREATE TABLE PRICES
(
    ID         UUID         PRIMARY KEY,
    BRAND_ID   BIGINT       NOT NULL,
    START_DATE TIMESTAMP    WITHOUT TIME ZONE NOT NULL,
    END_DATE   TIMESTAMP    WITHOUT TIME ZONE NOT NULL,
    PRICE_LIST BIGINT       NOT NULL,
    PRODUCT_ID BIGINT       NOT NULL,
    PRIORITY   VARCHAR2(50) NOT NULL,
    PRICE      NUMERIC(6,2) NOT NULL,
    CURR       VARCHAR2(4)  NOT NULL
);

CREATE INDEX PRICES_INDEX ON PRICES(BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);